[package]
name = "appinsights"
version = "0.1.0"
authors = ["dmolokanov <dmolokanov@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
chrono = "0.4.9"

[dev-dependencies]
test-case = "0.3.3"