[package]
name = "appinsights"
version = "0.1.0"
authors = ["dmolokanov <dmolokanov@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
chrono = { version = "0.4.9", features = ["serde"] }
http = "0.1.19"
uuid = { version = "0.8.1", features = ["v4"] }
reqwest = { version = "0.10.0-alpha.2", features = ["blocking", "json"] }
log = "0.4.8"

[dev-dependencies]
test-case = "0.3.3"