[package]
name = "appinsights"
version = "0.1.0"
authors = ["dmolokanov <dmolokanov@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.42"
chrono = { version = "0.4.10", features = ["serde"] }
http = "0.1.20"
uuid = { version = "0.8.1", features = ["v4"] }
reqwest = { version = "0.9.22" }
log = "0.4.8"
crossbeam-channel = "0.4.0"
sm = "0.9.0"

[dev-dependencies]
test-case = "0.3.3"
env_logger = "0.7.1"
